services:
  - type: web
    name: budgetmap-api
    env: docker
    plan: free # Cambiar a 'starter' si necesitas más recursos en producción
    region: ohio
    # healthCheckPath: /health # Actívalo si configuras Spring Boot Actuator
    envVars:
      # Render inyecta el puerto dinámicamente, aseguramos que Spring Boot lo escuche
      - key: SERVER_PORT
        value: "8080"
      # Base de Datos (NO PONER CLAVES AQUÍ, sync: false obliga a ponerlas manual en la UI de Render)
      - key: SPRING_DATASOURCE_URL
        sync: false 
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      # Seguridad (Tokens)
      - key: JWT_SECRET
        sync: false
      # Pasarela de Pagos
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false